server:
  port: 8085

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka.client.service-url.defaultZone }

spring:
  application:
    name: comment-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring.datasource.master.jdbc-url}
    username: ${spring.datasource.master.username}
    password: ${spring.datasource.master.password}

#  datasource:
#    master:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: ${spring.datasource.master.jdbc-url}
#      username: ${spring.datasource.master.username}
#      password: ${spring.datasource.master.password}
#
#    slave:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: ${spring.datasource.slave.jdbc-url}
#      username: ${spring.datasource.slave.username}
#      password: ${spring.datasource.slave.password}

  kafka:
    bootstrapAddress: ${spring.kafka.bootstrapAddress}
    commentTopic: commentCount
    commentGroup: commentCountGroup


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
